### ISSUE TITLE
Make Movement less stiff

### ISSUE THREAD

**Issue by ErikRospo** [Vitzual/NeonSundown#4]
Currently, the movement feels a bit stiff. Maybe adding in some lerp to the movement could help? Make it so that the player drifts a bit?

**Comment by andr9528** [comment]
Would also help, i think, if the player was knocked back slightly when hit.

**Comment by Vitzual** [comment]
In testing I've found this to be a bit annoying. Being able to fully stop on a whim lets you have full control over your movement, whereas drifting can easily result in sliding into enemies accidentally. Knockback can also have the same result where you get hit by one enemy and than accidentally slide into another, causing you to lose control and possibly die from a chain reaction.
